### ISSUE TITLE
Bots stop responding after some time using the site.

### ISSUE THREAD

**Issue by Hayniky** [GlizzyChief/SillyTavern-1.8.4-fix#23]
After some time using the site, the bots simply stop responding and the following message appears:

!!!!!!!!!!!! NEED TO PURGE -1 MESSAGES!
Error: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:452:15)
    at async #evaluate (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:384:60)
    at async ExecutionContext.evaluateHandle (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:325:16)
    at async IsolatedWorld.evaluateHandle (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:88:16)
    at async CdpJSHandle.evaluateHandle (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/api/JSHandle.js:150:20)
    at async CdpElementHandle.evaluateHandle (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:344:20)
    at async CSSQueryHandler.queryOne (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/common/QueryHandler.js:130:59)
    at async CdpElementHandle.$ (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:399:21)
    at async CdpElementHandle.<anonymous> (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/api/ElementHandle.js:268:32)
    at async CdpFrame.$ (/data/data/com.termux/files/home/SillyTavern-1.8.4-fix/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:376:20)
DEBUG: Current page title during SEND: New chat - Poe
Waiting for message...
After test manipulation: false

**Comment by GlizzyChief** [comment]
Hi! The error is very similar to what happens when the site goes to another page during script execution. Could you please tell me approx. how many messages it took, which bot, and if there's been anything you could notice visually? I'll look into it

**Comment by Hayniky** [comment]
I don't know exactly how many messages it took, but something I was able to notice visually was when I clicked the generate reply button for the second time, which made the button disappear.

**Comment by Hayniky** [comment]
Hh

**Comment by Hayniky** [comment]
I don't know exactly how many messages it took, but something I was able to notice visually was when I clicked the generate reply button for the second time, which made the button disappear.@GlizzyChief

**Comment by GlizzyChief** [comment]
Hi @Hayniky ! Sorry for the late response, I had a lot of stuff to attend to. Could you please send a screenshot if you encounter it again? It could also be related to new token system. Seems like Poe now requires tokens for pretty much everything
